version: '3'
services:
  #mongo container
  mongodb:
    image: mongo:latest
    container_name: dogs_db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root1234
    volumes:
      - dogs_data:/data/db
    networks:
      - my_network

  #redis container
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - my_network

  #rest-flask-api container
  flask-app:
    build: .
    image: emmanuel/dog_api_1.0.0
    container_name: flask_app
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - mongodb
      - redis
    environment:
      - FLASK_ENV=development
      - REDIS_URL=redis://redis:6379/0
    networks:
      - my_network

#volume for data persistence
volumes:
  dogs_data:

#network for container communication
networks:
  my_network:
    driver: bridge
